version: '2'
services:
  web:
    image: nginx:latest
    ports:
     - "8080:80"
    volumes:
     - ..:/src
     - ./server.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm-alpine
    volumes:
     - ..:/src
     - ./php.conf:/usr/local/etc/php-fpm.d/zzz.conf
